package responses

var ProductNotFound string = "Product not found"
var ProductSuccessfullyDeleted string = "Product was successfully deleted from the database"
var ProductsOutOfRange string = "Page number is out of range"
var InvalidPageNo string = "Invalid Page Number. Please enter a Valid integer"
var InvalidItemsPerPage string = "Invalid Items per Page. Please enter a Valid integer"
var ProductAlreadyExists string = "Product with this ID already exists"
var BadRequestBody string = "Bad Request Body"
var ProductAddedSuccessfully = "Product was added Successfully"
var MissingFields string = "Missing Fields: "
var InvalidDataTypeForFieldInJSONBody string = "Invalid Datatype for one/more fields in the Request body: "
var FollowingFieldsCannotBeNegative string = "The Following Fields cannot be Negative: "
var InvalidFieldsInRequestBody string = "Invalid Field detected in Request Body: "
var InvalidCategoryIDForProductFKConstraint string = "Invalid CategoryID"
var ProductIDCannotBeUpdated string = "ProductID cannot be Updated"
var ProductUpdatedSuccessfully string = "Product was updated Successfully"
var EmptyInputJson string = "The Input JSON is empty in the request body"
var InvalidCategoryID string = "Invalid Category ID"
var CategorySuccessfullyDeleted string = "Category was Successfully deleted from the database"
var CategoryIDUsedByProduct string = "This Category is being used in the product table and cannot be deleted"
var CategoryAlreadyExist string = "Category with this ID already exists"
var CategoryAddedSuccessfully string = "Category was added Successfully"
var CategoryIDCannotBeUpdated string = "CategoryID cannot be Updated"
var CategoryUpdatedSuccessfully string = "Category was Updated Successfully"
var ProductNotInInventory string = "Product is not in the Inventory"
var InventoryQuantityLessThanRequiredRemoval string = "Inventory quantity is less than the amount you are trying to remove"
var InventoryUpdatedSuccessfully = "Inventory items was updated Successfully"
var ErrorCreatingCart string = "An Error occurred while creating your cart. Please try again"
var InvalidCart string = "Cart Reference is Invalid"
var ReqQuantityMoreThanStock string = "The Required Quantity is more than the Available Inventory Quantity: "
var ItemAddedToCart string = "Item was added to the cart Sucessfully"
var ProductNotInCart string = "Product is not present in your Cart"
var CartQuantityLessThanRequiredRemoval string = "Cart quantity is less than the amount you are trying to remove"
var CartItemsRemovedSuccessfully string = "Cart Item(s) were removed Successfully"

var ServerStarted string = "Server running on PORT 8080"
